server: 
  port: 8081
spring:
   kafka:
     producer:
        bootstrap-servers: localhost:9092
     consumer:
        bootstrap-servers: localhost:9092
        group-id: demogroup
        auto-offset-reset: earliest